"""API endpoints for v6task_finance_task_014.

Generated by Tasker (finance frontend feature companion endpoint).
Frontend featureApi.ts calls GET /api/v6task-finance-task-014.
"""
from fastapi import APIRouter

router = APIRouter()


@router.get("/api/v6task-finance-task-014")
def v6task_finance_task_014_items():
    """Return feature items for v6task_finance_task_014 (companion endpoint)."""
    return {"items": [], "task_id": "v6task_finance_task_014"}
