"""API endpoints for v6task_finance_task_008.

Generated by Tasker (frontend feature companion endpoint).
Frontend featureApi.ts calls GET /api/v6task-finance-task-008.

2026-08-04 根治：不再返回硬编码空壳 {"items": []}——生成带样例数据的骨架，
调用方（FeaturePanel/featureApi）能立即渲染真实列表；业务接入真实数据源后替换。
"""

from fastapi import APIRouter

router = APIRouter()

_SAMPLE_ITEMS = [
    {
        "id": "sample-1",
        "title": "示例记录 1",
        "status": "active",
        "createdAt": "2026-01-01T00:00:00Z",
    },
    {
        "id": "sample-2",
        "title": "示例记录 2",
        "status": "draft",
        "createdAt": "2026-01-02T00:00:00Z",
    },
]


@router.get("/api/v6task-finance-task-008")
def v6task_finance_task_008_items():
    """Return feature items for v6task_finance_task_008 (companion endpoint)."""
    return {"items": _SAMPLE_ITEMS, "task_id": "v6task_finance_task_008"}
